### ISSUE TITLE
Logic issues & inaccuracy

### ISSUE THREAD

**Issue by Suntrie** [dVede/Table#1]
1. Что произойдёт в методе `inRange`, если таблица будет пустой?

2. Конструкции вида:
` if (toAdd == null)
            throw new NullPointerException();`
в `add(..)/ removePoint(..)` - бессмысленны, так как Вы выбрасываете всё тот же неинформативный NPE. Есть следующие альтернативы: 

- оставить `NPE` и документировать, в каких случаях он выбрасывается / кастомизировать сообщение или тип исключения;

- добавить аннотации - см. файл на гуглдиске;

- возвращать осмысленные специальные значения.

3.  ` if (table.add(toAdd))
            return table.add(toAdd);        
        else
            return false;`
Нельзя ли это упростить?

4. Пожалуйста, называйте пакеты в соответствии с одной из распространённых нотаций - например, [Google Java style guide](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names).

**Comment by dVede** [comment]
Done

**Comment by dVede** [comment]
Done
