### ISSUE TITLE
Tests improvement

### ISSUE THREAD

**Issue by Suntrie** [dVede/Table#2]
1. В тестах не должно быть методов, в которых Вы не реализуете проверки с применением assert, `sout` - точно не лучшее решение в отладке кода, при необходимости лучше воспользоваться дебаггером;

2. В данный момент не проверяются ветки true для `addPoint(..)/ removePoint(..)`, и выкидываемые Вами `NPE`;

3. Дублирующийся код стоит выносить во вспомогательные функции.

**Comment by dVede** [comment]
Done
